src/OnlineEdx/Applications/OnlineEdx.Web/Controllers/EnrollmentController.cs
using Autofac;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OnlineEdx.Web.Models;

namespace OnlineEdx.Web.Controllers
{
    [Authorize]
    public class EnrollmentController : BaseController<EnrollmentController>
    {
        public EnrollmentController(ILogger<EnrollmentController> logger, ILifetimeScope scope) : base(logger, scope)
        {
        }

        public IActionResult Index()
        { 
            var model = _scope.Resolve<EnrollCourseModel>();
            model.LoadEnrolledCourses();
            return View(model);
        }

        public async Task<JsonResult> EnrollCourse(Guid id)
        {
            try
            {
                var model = _scope.Resolve<EnrollCourseModel>();
                await model.EnrollAsync(id);
                return Json(true);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                return Json(ex.Message);
            }
        }
    }
}

src/OnlineEdx/Applications/OnlineEdx.Web/Views/Shared/_EnrollScriptPartial.cshtml
<script>
    function Enroll(id) {
        $.ajax({
            url: '@Url.Action("EnrollCourse", "Enrollment")',
            type: 'GET',
            dataType: 'json',
            cache: false,
            data: { 'id': id },
            success: function (results) {
                if (results == true) {
                    toastr.success("Course successfully enrolled.");
                    return;
                }
                toastr.error(results);
            },
            error: function () {
                toastr.error('You must be logged in to enroll course.');
            }
        });
    }
</script>

src/OnlineEdx/Applications/OnlineEdx.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Type some info">
    <meta name="author" content="Type name">

    <title>OnlineEdx | Free Online Courses by Onnorokom Software</title>

    <!-- Bootstrap css -->
    <link href="~/alistyle/css/bootstrap.css?v=2.0" rel="stylesheet" type="text/css" />
    <!-- Toastr css -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" type="text/css" rel="stylesheet">
    <!-- Custom css -->
    <link href="~/alistyle/css/ui.css?v=2.0" rel="stylesheet" type="text/css" />
    <link href="~/alistyle/css/responsive.css?v=2.0" rel="stylesheet" type="text/css" />

    <!-- Font awesome 5 -->
    <link href="~/alistyle/fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">

    <style>
        .section-content {
            min-height: 82vh;
        }
    </style>
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>

    <header class="section-header border-bottom">

        <nav class="navbar navbar-expand-xl navbar-light">
            <div class="container">
                <a class="navbar-brand" asp-action="Index" asp-controller="Home">
                    <img src="~/admintheme/images/logo.svg" height="40" class="logo">
                </a>

                <div class="d-flex align-items-center">
                    <div class="d-xl-none me-2">
                        <a asp-action="Login" asp-controller="Account" class="btn btn-light"> <i class="fa fa-user"></i> </a>
                        <a asp-action="Index" asp-controller="Enrollment" class="btn btn-light"> My Courses</a>
                    </div>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar_main" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>

                <div class="collapse navbar-collapse" id="navbar_main">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Home">Home </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Course" asp-route-name="">Courses</a>
                        </li>
                    </ul>

                    <form class="me-3">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search">
                            <button class="btn-icon btn-light btn">  <i class="fa fa-search"></i> </button>
                        </div>
                    </form> <!-- form end.// -->
                    <div class="widgets-wrap d-none d-xl-flex">
                        <partial name="_LoginPartial"/>
                    </div>
                </div> <!-- collapse end.// -->
            </div> <!-- container end.// -->
        </nav> <!-- navbar end.// -->

    </header> <!-- section-header end.// -->

    <section class="section-content bg padding-y">
        <partial name="_ResponsePartial"/>
        @RenderBody()
    </section> <!--   SECTION CONTENT END.//   -->
    <footer class="section-footer bg-white shadow">
        <div class="container">
            <section class="footer-main padding-y">
                <div class="row">
                    <aside class="col-lg-4 col-12">
                        <article class="me-lg-4 mb-4">
                            <h6 class="title">Contact us</h6>
                            <ul class="list-icon">
                                <li class="mb-2">
                                    <i class="icon fa fa-map-marker"></i>
                                    Moscow, Russia, Fake Street, <br>
                                    Area name, PO 10021
                                </li>
                                <li class="mb-2">
                                    <i class="icon fa fa-phone"></i>   (800) 060-0730, (800) 060-0730
                                </li>
                                <li class="mb-2">
                                    <i class="icon fa fa-envelope"></i>    info@mywebsite.com
                                </li>
                            </ul>
                        </article>
                    </aside> <!-- col end.// -->

                    <aside class="col-lg col-6">
                        <h6 class="title">Company</h6>
                        <ul class="list-menu mb-4">
                            <li>  <a href="#"> About us </a> </li>
                            <li>  <a href="#"> Career </a> </li>
                            <li>  <a href="#"> Find a store </a> </li>
                            <li>  <a href="#"> Rules and terms </a> </li>
                            <li>  <a href="#"> Sitemap </a> </li>
                        </ul>
                    </aside> <!-- col end.// -->

                    <aside class="col-lg col-6">
                        <h6 class="title"> Services </h6>
                        <ul class="list-menu mb-4">
                            <li>  <a href="#"> Help Center </a> </li>
                            <li>  <a href="#"> Money refund </a> </li>
                            <li>  <a href="#"> Order status </a> </li>
                            <li>  <a href="#"> Shipping info </a> </li>
                            <li>  <a href="#"> Open dispute </a>  </li>
                        </ul>
                    </aside> <!-- col end.// -->

                    <aside class="col-lg col-6">
                        <h6 class="title"> User center </h6>
                        <ul class="list-menu mb-4">
                            <li>  <a href="#"> Register </a> </li>
                            <li>  <a href="#"> Sign in </a> </li>
                            <li>  <a href="#"> Restore account </a> </li>
                            <li>  <a href="#"> Track order </a>  </li>
                        </ul>
                    </aside> <!-- col end.// -->

                    <aside class="col-lg col-6">
                        <h6 class="title">Social</h6>
                        <ul class="list-icon list-menu mb-4">
                            <li><a href="#"> <i class="icon fab fa-facebook"></i> Facebook </a></li>
                            <li><a href="#"> <i class="icon fab fa-twitter"></i> Twitter </a></li>
                            <li><a href="#"> <i class="icon fab fa-instagram"></i> Instagram </a></li>
                            <li><a href="#"> <i class="icon fab fa-youtube"></i> Youtube </a></li>
                        </ul>
                    </aside>

                </div> <!-- row end.// -->
            </section>

            <section class="footer-bottom d-flex justify-content-between border-top">
                <p class="text-muted mb-0"> &copy; 2021 Templatemount. All rights reserved.  </p>
                <div>
                    <i class="fab fa-lg fa-cc-visa"></i>
                    <i class="fab fa-lg fa-cc-amex"></i>
                    <i class="fab fa-lg fa-cc-mastercard"></i>
                    <i class="fab fa-lg fa-cc-paypal"></i>
                </div>
            </section>

        </div> <!-- container end.// -->
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/alistyle/js/script.js?v=1.0"></script>
    <!-- Toastr css -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/OnlineEdx/Applications/OnlineEdx.Web/Views/Shared/_ResponsePartial.cshtml
@using OnlineEdx.Web.Extensions
@if(TempData.Peek<ResponseModel>("ResponseMessage") != null)
{
    var response = TempData.Get<ResponseModel>("ResponseMessage");
        <script type="text/javascript">
            window.onload = function () {
                toastr.@(response.Type.ToString().ToLower())('@response.Message');
            };
        </script>
}